#version: "3.7"
#services:
#  server:
#    container_name: appserver
#    image: nonso/week9_fashionBlog
#    environment:
#      MYSQL_DATABASE
#    build: .
#      restart: always
#        ports:
#          - 8082:8080
#        depends_on:
#          - mysqldb
#  mysqldb:
#    platform: linux/x86_64
#    image: "mysql:8.0.29"
#    restart: always
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: fashion
#      MYSQL_ROOT_PASSWORD: bravenonso22
#      MYSQL_ROOT_USERNAME: root